---
layout: cv
title: Conner Brown's Resume
---
# Conner Brown
Business Analyst

<div id="webaddress">
<a href="cbrown9799@byui.edu">cbrown9799@byui.edu</a>
| <a href="http://www.linkedin.com/in/conner-brown-">LinkedIn</a>
</div>

## Currently

Pursuing a Bachelor of Business Analytics at Brigham Young University - Idaho

### Specialized in

Data Analysis, Financial Modeling, SQL & Database Management, Power BI & Data Visualization

### Research interests

Business Intelligence, Predictive Analytics, Financial Forecasting, Machine Learning Applications in Business

## Education

`2020 - December 2024`
__Brigham Young University - Idaho, Rexburg, ID__

- Bachelor of Business Analytics
- Minor in Business Finance

## Awards

`2023`
Dean's List, *Brigham Young University - Idaho*

## Experience

`February 2022 - Present`
__In House Technician__, Safe Streets USA (Authorized provider of ADT Security System), Rexburg, ID

- Maintained good relations with customers experiencing issues with security systems.
- Troubleshooted security system components like cameras, sensors, and panels.
- Assisted escalated customers over the phone, providing solutions and ensuring satisfaction.

`April 2021 - September 2021`
__Mosquito Field Service Technician__, Benton County Mosquito Control District, Richland, WA

- Supervised an area of land, developing skills in pesticide application and customer relations.
- Monitored over 100 areas weekly, ensuring the county was free from mosquito-related dangers.

`April 2020 - September 2020`
__Package Handler__, FedEx, Pasco, WA

- Managed a group of workers loading and preparing packages during the coronavirus pandemic.
- Awarded Employee of the Month in July and August for teamwork, integrity, and responsibility.

`October 2018 - April 2020`
__Full-Time Volunteer Representative__, The Church of Jesus Christ of Latter-day Saints, Saltillo, Mexico

- Served as a full-time volunteer, setting and achieving goals and providing service to others.
- Developed work habits and communication skills, working in a foreign community.

`August 2018 - October 2018`
__Potato Harvest Worker__, Agri Northwest Farms, Plymouth, WA

- Oversaw potato sheds and a group of workers during the harvest season.
- Gained endurance, responsibility, and experience through labor-intensive work.

## Skills

- English (Native), Spanish (Fluent)
- Microsoft Office (Word, Excel, PowerPoint Certification)
- Ability to work in fast-paced and intense environments




<!-- ### Footer

Last updated: September 2024 -->